#!/bin/bash

# Please don't change this.
MAX_POINTS=100

# TODO 1: Function check for task 1
test_p1() {
	n_tests=20
	src_names=(p1.c p1.cpp P1.java)
	tests=($(seq 0 $(($n_tests - 1))))
	points=($(printf '1.5 %.0s' $(seq 0 $(($n_tests - 1)))))
	pmax=30

	run_problem p1 1
}

#TODO 2: Function check for task 2
test_p2() {
	n_tests=20
	src_names=(p2.c p2.cpp P2.java)
	tests=($(seq 0 $(($n_tests - 1))))
	points=($(printf '1.5 %.0s' $(seq 0 $(($n_tests - 1)))))
	pmax=30

	run_problem p2 2
}

# TODO 3: Function check for task 3
test_p3() {
	n_tests=25
	src_names=(p3.c p3.cpp P3.java)
	tests=($(seq 0 $(($n_tests - 1))))
	points=($(printf '1.6 %.0s' $(seq 0 $(($n_tests - 1)))))
	pmax=40
	run_problem p3 3
}

# TODO 4: Put your tasks in this function
test_homework() {
	if [[ "$1" = "1" || "$1" = "p1" ]]; then
	 	test_p1
	elif [[ "$1" = "2" || "$1" = "p2" ]]; then
        test_p2
	elif [[ "$1" = "3" || "$1" = "p3" ]]; then
        test_p3
	elif [[ "$1" = "cs" ]]; then
		echo "skip running tests"
	else
		test_p1
		test_p2
        test_p3
	fi
}

# Please don't change this.
source "$(dirname "{0}")"/_utils/base_check.sh
